config/routes.rb
Rails.application.routes.draw do
  resources :categories
  	resources :articles do
    	resources :comments, only: [:create, :destroy, :update]
  	end
  
  devise_for :users  
  get 'inicio/index'
  root 'inicio#index'

 
end

app/models/article.rb
class Article < ActiveRecord::Base

	include AASM

	belongs_to :user
	has_many :comments
	has_many :has_categories
	has_many :categories, through: :has_categories


	validates :title, presence: true, uniqueness: true
	validates :body, presence: true
	before_save :set_visits_count
	after_create :save_categories

	def categories=(value)
		@categories = value
	end

	def update_visits_count
		self.update(visits_count: self.visits_count + 1)
	end

	
	def set_visits_count
		self.visits_count ||= 0
	end	

	aasm column: "state" do
		state :in_draft, initial: true
		state :published

		event :publish do
			transitions from: :in_draft, to: :published
		end

		event :unpublish do
			transitions from: :published, to: :in_draft
		end
	end


	private

	def save_categories
		@categories.each do |category_id|
			HasCategory.create(category_id: category_id,article_id: self.id)
		end
	end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles
  has_many :comments
  include PermissionsConcern
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_categories

  protected


	def authenticate_editor!
		redirect_to root_path unless user_signed_in? && current_user.is_editor?
	end

	def authenticate_admin!
		redirect_to root_path unless user_signed_in? && current_user.is_admin?
	end

  private

  def set_categories
  	@categories = Category.all
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, except: [:index, :new, :create ]
  before_action :authenticate_user!, except: [:show, :index]
  before_action :authenticate_editor!, only: [:new, :create, :update]
  before_action :authenticate_admin!, only: [:destroy]
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article.update_visits_count
    @comment = Comment.new
  end

  # GET /articles/new
  def new
    @article = Article.new
    @categories = Category.all
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.new(article_params)
    @article.categories = params[:categories]

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :categories)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:update, :destroy]
  before_action :set_article
    before_action :authenticate_user!

  def create
    @comment = current_user.comments.new(comment_params)
    @comment.article = @article
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.article, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment.article, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @article, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_article
      @article = Article.find(params[:article_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :article_id, :body)
    end
end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">

      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
 
   <div class="field">
    <%= f.text_field :title, placeholder: "Titulo", class:"form-control"%>
  </div>
  <div class="field">
    <%= f.text_area :body, placeholder: "Escribe aquí el artículo", style:"height:250px; width:100%", class:"form-control" %> 
  </div>

  <div class="field">
    <label>Categorias</label>
      <% @categories.each do |category| %>
        <div class="field">
        <%= check_box_tag "categories[]", category.id %> <%= category.name %>
        </div>
      
    <% end %>
  </div>
  
<%= f.hidden_field :user_id, :value => current_user.id %>
  <div class="actions">
    <%= f.submit "Guardar"%>
  </div>
<% end %>
 
  

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articulos</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Cuerpo</th>
      <th>Visitas</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <h1><td><%= article.title %></td></h1>
        <td><%= article.body %></td>
        <td><%= article.visits_count %></td>
        <td><%= link_to 'Leer', article %></td>
        <td><%= link_to 'Editar', edit_article_path(article) %></td>
        <td><%= link_to 'Eliminar', article, method: :delete, data: { confirm: 'Preciona aceptar si quieres eliminar el Articulo' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Crear nuevo Articulo', new_article_path %>

app/views/articles/new.html.erb
<div style="width:80%;margin:0 auto;">
<h1>Crear nuevo artículo</h1>

<%= render 'form' %>
<div class="btn">
	<%= link_to 'Atras', articles_path %>
</div>

</div>

app/views/articles/show.html.erb
<% unless @article.user.nil? %>

<p>
	Escrito por: <%= @article.user.email %>
</p>
<% end %>
<div class="field">
	<% @article.categories.each do |category| %>
	<%= link_to category.name, category,style:"color:#{category.color};" %>
	
	<% end %>
<p>
	Visitas: <%= @article.visits_count %>
</p>
<div>
	<%= @article.body %>
</div>

<div class="field">
	<h3>Comentarios</h3>
	<%= render "comments/form" %>
	<ul>
	  <% @article.comments.each do |comment| %>
		<li>
		  <%= comment.user.email %> <br>
		  <h4><%= comment.body %> </h4>
		</li>
	  <%end%>
	</ul>

</div>

<%= link_to 'Editar', edit_article_path(@article) %> |
<%= link_to 'Volver', articles_path %>

app/views/comments/_form.html.erb
<%= form_for([@article, @comment], remote: true) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/inicio/index.html.erb
<% if user_signed_in? %>
<center><h1>Bienvenido <%= current_user.email %></h1></center>

<% else user_signed_in? %>
<center><H1>Bienvenidos a mi Blog</H1></center>
<% end -%>


<br>
<br>

<div class="col-md col-xs">
	<center><p>
		Aquí podras encontrar actualizaciones diarias sobre mis libros favoritos, proximos lanzamientos de las sagas que actualmente estoy leyendo.
	</p></center>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rivendel el concilio</title>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css" integrity="sha384-aUGj/X2zp5rLCbBxumKTCw2Z50WgIr1vs/PFN4praOTvYXWlVyh2UtNUU0KAUhAX" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>



  <link href='https://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 
<header>
  <nav class="be-dark white large-padding">
    <ul class="no-list row center-xs middle-xs">
       <div class="col-md col-xs">
          <h1 class="no-margin" id="logo"><%= link_to "Rivendel el Concilio", root_path %> </h1>
      
       </div>
    

    <div class="col-md col-xs">
      <%= link_to "Articulos", articles_path %>
    </div>  
    
    
    <% @categories.each do |category| %>
      <div class="col-md col-xs">
       <%= link_to category.name,category %>
      </div>  
    <%end%>  

      <% if user_signed_in? %>
    <div class="col-md col-xs">
      <a href="<%= edit_user_registration_path(current_user) %>">Editar Perfil </a> 
    </div>
    <div class="col-md col-xs">
      <a href="<%= destroy_user_session_path %>", data-method="delete">Cerrar Session </a> 
    </div>
  <% else %>
    <div class="col-md col-xs"><a href="<%= new_user_session_path %>">Ingresar </a>  </div>
    <div class="col-md col-xs"><a href="<%= new_user_registration_path %>">Registrarse </a>  </div>
    <% end -%>
    
      </ul>
    </form>
  </section>

    </div>
 
    </ul>
  </nav>
  <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>
 </header>


<%= yield %>

</body>


</html>